name: Manual Deployment

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
    
  workflow_dispatch:
     inputs:
        DATA:
          description: 'Log level'
          default: 'Help'
        
env:
  DATA_ENV : ${{ github.event.inputs.DATA }}
#       logLevel:
#         description: 'Log level'     
#         required: true
#         default: 'warning'
#       tags:
#         description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:        
    - name: Build with Maven
      run: |
             echo "Hello $DATA_ENV"
