# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Test with Maven
      run: mvn clean test
      
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: us-east-1
        
    - name: AWS CodeArtifact Auth
      uses: advancedcsg-open/actions-aws-codeartifact-auth@v1.0.0
      with:
        region: us-east-1
        domain: poc
        domain-owner: 629326733698
        duration: 900
        
    - name: Build with Maven
      run: |
             mvn -s settings.xml clean package deploy
             
    - name: SSH Execute Commands
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        command: |
                echo "Deploy"
                echo "Deploy2"
        hosts: 54.80.53.41
        privateKey: ${{ secrets.PEM_KEY }}

